const CREAR_CUENTA = 'CREAR_CUENTA';
const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
const REGISTRO_FALLIDO = 'REGISTRO_FALLIDO';

const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
const LOGOUT = 'LOGOUT';

export {
    CREAR_CUENTA,
    REGISTRO_EXITOSO,
    REGISTRO_FALLIDO,
    LIMPIAR_ALERTA,
    USUARIO_AUTENTICADO,
    LOGIN_ERROR,
    LOGIN_EXITOSO,
    LOGOUT

    
}