const CREAR_CUENTA = 'CREAR_CUENTA';
const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
const REGISTRO_FALLIDO = 'REGISTRO_FALLIDO';
const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

export {
    CREAR_CUENTA,
    REGISTRO_EXITOSO,
    REGISTRO_FALLIDO,
    LIMPIAR_ALERTA
    
}