const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
const AUTENTICAR_CUENTA = 'AUTENTICAR_CUENTA';
const CREAR_CUENTA = 'CREAR_CUENTA';

export {
    USUARIO_AUTENTICADO,
    AUTENTICAR_CUENTA,
    CREAR_CUENTA
}